# Generated by Django 5.0.6 on 2024-05-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_price_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
