# Generated by Django 5.0.6 on 2024-05-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
